export type KeyData = {
  id: string;
  src: string;
  left: number;
  top: number;
  width: number;
  height: number;
};

export const keys: KeyData[] = [
  { id: "Backquote", src: "/assets/keys/top.png", left: 2, top: -1, width: 5, height: 3 },
  { id: "Digit1", src: "/assets/keys/top.png", left: 7, top: -1, width: 5, height: 3 },
  { id: "Digit2", src: "/assets/keys/top.png", left: 12, top: -1, width: 5, height: 3 },
  { id: "Digit3", src: "/assets/keys/top.png", left: 17, top: -1, width: 5, height: 3 },
  { id: "Digit4", src: "/assets/keys/top.png", left: 22, top: -1, width: 5, height: 3 },
  { id: "Digit5", src: "/assets/keys/top.png", left: 27, top: -1, width: 5, height: 3 },
  { id: "Digit6", src: "/assets/keys/top.png", left: 32, top: -1, width: 5, height: 3 },
  { id: "Digit7", src: "/assets/keys/top.png", left: 37, top: -1, width: 5, height: 3 },
  { id: "Digit8", src: "/assets/keys/top.png", left: 42, top: -1, width: 5, height: 3 },
  { id: "Digit9", src: "/assets/keys/top.png", left: 47, top: -1, width: 5, height: 3 },
  { id: "Digit0", src: "/assets/keys/top.png", left: 52, top: -1, width: 5, height: 3 },
  { id: "Minus", src: "/assets/keys/top.png", left: 57, top: -1, width: 5, height: 3 },
  { id: "Equal", src: "/assets/keys/top.png", left: 62, top: -1, width: 5, height: 3 },
  { id: "Backspace", src: "/assets/keys/backspace.png", left: 67, top: -1, width: 11, height: 3 },
  { id: "Tab", src: "/assets/keys/tab.png", left: 2, top: 2, width: 7, height: 3 },
  { id: "KeyQ", src: "/assets/keys/mid.png", left: 9, top: 2, width: 5, height: 3 },
  { id: "KeyW", src: "/assets/keys/mid.png", left: 14, top: 2, width: 5, height: 3 },
  { id: "KeyE", src: "/assets/keys/mid.png", left: 19, top: 2, width: 5, height: 3 },
  { id: "KeyR", src: "/assets/keys/mid.png", left: 24, top: 2, width: 5, height: 3 },
  { id: "KeyT", src: "/assets/keys/mid.png", left: 29, top: 2, width: 5, height: 3 },
  { id: "KeyY", src: "/assets/keys/mid.png", left: 34, top: 2, width: 5, height: 3 },
  { id: "KeyU", src: "/assets/keys/mid.png", left: 39, top: 2, width: 5, height: 3 },
  { id: "KeyI", src: "/assets/keys/mid.png", left: 44, top: 2, width: 5, height: 3 },
  { id: "KeyO", src: "/assets/keys/mid.png", left: 49, top: 2, width: 5, height: 3 },
  { id: "KeyP", src: "/assets/keys/mid.png", left: 54, top: 2, width: 5, height: 3 },
  { id: "BracketLeft", src: "/assets/keys/mid.png", left: 59, top: 2, width: 5, height: 3 },
  { id: "BracketRight", src: "/assets/keys/mid.png", left: 64, top: 2, width: 5, height: 3 },
  { id: "Enter", src: "/assets/keys/return.png", left: 69, top: 2, width: 9, height: 3 },
  { id: "CapsLock", src: "/assets/keys/caps.png", left: 2, top: 5, width: 9, height: 3 },
  { id: "KeyA", src: "/assets/keys/mid.png", left: 11, top: 5, width: 5, height: 3 },
  { id: "KeyS", src: "/assets/keys/mid.png", left: 16, top: 5, width: 5, height: 3 },
  { id: "KeyD", src: "/assets/keys/mid.png", left: 21, top: 5, width: 5, height: 3 },
  { id: "KeyF", src: "/assets/keys/mid.png", left: 26, top: 5, width: 5, height: 3 },
  { id: "KeyG", src: "/assets/keys/mid.png", left: 31, top: 5, width: 5, height: 3 },
  { id: "KeyH", src: "/assets/keys/mid.png", left: 36, top: 5, width: 5, height: 3 },
  { id: "KeyJ", src: "/assets/keys/mid.png", left: 41, top: 5, width: 5, height: 3 },
  { id: "KeyK", src: "/assets/keys/mid.png", left: 46, top: 5, width: 5, height: 3 },
  { id: "KeyL", src: "/assets/keys/mid.png", left: 51, top: 5, width: 5, height: 3 },
  { id: "Semicolon", src: "/assets/keys/mid.png", left: 56, top: 5, width: 5, height: 3 },
  { id: "Quote", src: "/assets/keys/mid.png", left: 61, top: 5, width: 5, height: 3 },
  { id: "Backslash", src: "/assets/keys/hashtag.png", left: 66, top: 5, width: 12, height: 3 },
  { id: "ShiftLeft", src: "/assets/keys/l_shift.png", left: 2, top: 8, width: 11, height: 3 },
  { id: "KeyZ", src: "/assets/keys/mid.png", left: 13, top: 8, width: 5, height: 3 },
  { id: "KeyX", src: "/assets/keys/mid.png", left: 18, top: 8, width: 5, height: 3 },
  { id: "KeyC", src: "/assets/keys/mid.png", left: 23, top: 8, width: 5, height: 3 },
  { id: "KeyV", src: "/assets/keys/mid.png", left: 28, top: 8, width: 5, height: 3 },
  { id: "KeyB", src: "/assets/keys/mid.png", left: 33, top: 8, width: 5, height: 3 },
  { id: "KeyN", src: "/assets/keys/mid.png", left: 38, top: 8, width: 5, height: 3 },
  { id: "KeyM", src: "/assets/keys/mid.png", left: 43, top: 8, width: 5, height: 3 },
  { id: "Comma", src: "/assets/keys/mid.png", left: 48, top: 8, width: 5, height: 3 },
  { id: "Period", src: "/assets/keys/mid.png", left: 53, top: 8, width: 5, height: 3 },
  { id: "Slash", src: "/assets/keys/mid.png", left: 58, top: 8, width: 5, height: 3 },
  { id: "ShiftRight", src: "/assets/keys/r_shift.png", left: 63, top: 8, width: 15, height: 3 },
  { id: "ControlLeft", src: "/assets/keys/l_ctrl.png", left: 2, top: 11, width: 7, height: 6 },
  { id: "MetaLeft", src: "/assets/keys/win.png", left: 9, top: 11, width: 6, height: 6 },
  { id: "AltLeft", src: "/assets/keys/win.png", left: 15, top: 11, width: 6, height: 6 },
  { id: "Space", src: "/assets/keys/space.png", left: 21, top: 11, width: 31, height: 6 },
  { id: "AltRight", src: "/assets/keys/win.png", left: 52, top: 11, width: 6, height: 6 },
  { id: "Fn", src: "/assets/keys/win.png", left: 58, top: 11, width: 6, height: 6 },
  { id: "MetaRight", src: "/assets/keys/win.png", left: 64, top: 11, width: 6, height: 6 },
  { id: "ControlRight", src: "/assets/keys/r_ctrl.png", left: 70, top: 11, width: 8, height: 6 },
];
